--OPÇÃO 1 DE IF.. COM BEGIN E END
IF OBJECT_ID('TABELA_TESTE', 'U') IS NOT NULL
BEGIN
	DROP TABLE TABELA_TESTE
END
CREATE TABLE TABELA_TESTE(ID VARCHAR(10))

--OPÇÃO 2
IF OBJECT_ID('TABELA_TESTE', 'U') IS NOT NULL 	DROP TABLE TABELA_TESTE
CREATE TABLE TABELA_TESTE(ID VARCHAR(10))

SELECT GETDATE()
SELECT DATENAME(WEEKDAY, DATEADD(DAY,4,GETDATE()))

DECLARE @DIA_SEMANA VARCHAR(20)
DECLARE @NUMERO_DIAS INT

SET @NUMERO_DIAS = 4
SET @DIA_SEMANA = DATENAME(WEEKDAY, DATEADD(DAY,@NUMERO_DIAS,GETDATE()))
PRINT @DIA_SEMANA
IF @DIA_SEMANA = 'Domingo' OR @DIA_SEMANA = 'Sabado'
	PRINT 'Este dia é fim de semana'
ELSE
	PRINT 'Este é um dia da semana'


--EXERCICIO TESTANDO O NUMERO D NOTASFISCAIS
DECLARE @DATA_ESCOLHIDA DATE
DECLARE @NUMERO_NOTAS INT 
SET @DATA_ESCOLHIDA = '20170102'

SELECT @NUMERO_NOTAS = COUNT(*) 
FROM [NOTAS FISCAIS] NF WHERE NF.DATA = @DATA_ESCOLHIDA

IF @NUMERO_NOTAS > 70
	PRINT 'Muita Nota'
ELSE
	PRINT 'POuca Nota'

PRINT @NUMERO_NOTAS