SELECT BAIRRO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES]
GROUP BY BAIRRO

DECLARE @LIMITE_MAXIMO FLOAT, @LIMITE_AUTAL FLOAT
DECLARE @BAIRRO VARCHAR(20)

SET @BAIRRO = 'Jardins'
SET @LIMITE_MAXIMO = 500000

SELECT @LIMITE_AUTAL = SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = @BAIRRO
IF @LIMITE_MAXIMO = (SELECT SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = @BAIRRO)
BEGIN
	PRINT 'Valore estourou, não e possivel abrir novos creditos.'
END 
ELSE
BEGIN
	PRINT 'Valor não estourou, é possivel abrir novos creditos.'
END

-- EXERCICIO --

DECLARE @DATANOTA DATE
DECLARE @NUMNOTAS INT
SET @DATANOTA = '20170102'

IF (SELECT  COUNT(*) FROM [NOTAS FISCAIS] WHERE DATA = @DATANOTA)>70
	PRINT 'MUITA NOTA'
ELSE
	PRINT 'POUCA NOTA'
	PRINT @NUMNOTAS