DECLARE @NOME VARCHAR(200)
DECLARE CURSOR1 CURSOR FOR SELECT TOP 4 NOME FROM [TABELA DE CLIENTES]
OPEN CURSOR1
FETCH NEXT FROM CURSOR1 INTO @NOME
WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT @NOME
	FETCH NEXT FROM CURSOR1 INTO @NOME
END

/** EXERCICIO AULA **/
DECLARE @LIMITE_DE_CREDITO FLOAT
DECLARE @LIMITE_TOTAL FLOAT
DECLARE CURSOR2 CURSOR FOR SELECT [LIMITE DE CREDITO] FROM [TABELA DE CLIENTES]
SET @LIMITE_DE_CREDITO = 0

OPEN CURSOR2
FETCH NEXT FROM CURSOR2 INTO @LIMITE_DE_CREDITO
WHILE @@FETCH_STATUS = 0
BEGIN
	SET @LIMITE_TOTAL= @LIMITE_TOTAL + @LIMITE_DE_CREDITO
	FETCH NEXT FROM CURSOR2 INTO @LIMITE_DE_CREDITO
END
CLOSE CURSOR2
DEALLOCATE CURSOR1
PRINT @LIMITE_TOTAL 

DECLARE @NOME VARCHAR(200)
DECLARE @ENDERECO VARCHAR(MAX)
DECLARE CURSOR10 CURSOR FOR
SELECT NOME, ([ENDERECO 1] + ' - ' + BAIRRO + ' - ' + CIDADE + ' - ' + ESTADO + ' - ' + CEP) ENDCOMPLETO FROM [TABELA DE CLIENTES]
OPEN CURSOR10
FETCH NEXT FROM CURSOR10 INTO @NOME, @ENDERECO
WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT @NOME + 'Endereço: ' + @ENDERECO
	FETCH NEXT FROM CURSOR10 INTO @NOME, @ENDERECO
END
DEALLOCATE CURSOR10



/** EXERCICIO AULA**/
DECLARE @QUANTIDADE INT
DECLARE @PRECO FLOAT
DECLARE @FATURAMENTOACUM DECIMAL(30,5)
DECLARE @MES INT
DECLARE @ANO INT
SET @MES = 1
SET @ANO = 2017
DECLARE CURSOR1 CURSOR FOR SELECT INF.QUANTIDADE, INF.PREÇO FROM [ITENS NOTAS FISCAIS] INF
							INNER JOIN [NOTAS FISCAIS] NF ON NF.NUMERO=INF.NUMERO
							WHERE MONTH(NF.DATA) =@MES AND YEAR(NF.DATA)=@ANO
SET @FATURAMENTOACUM=0
OPEN CURSOR1
FETCH NEXT FROM CURSOR1 INTO @QUANTIDADE, @PRECO
WHILE @@FETCH_STATUS=0
BEGIN
	SET @FATURAMENTOACUM = @FATURAMENTOACUM + (@QUANTIDADE * @PRECO)
	FETCH NEXT FROM CURSOR1 INTO @QUANTIDADE, @PRECO
END
CLOSE CURSOR1
DEALLOCATE CURSOR1
PRINT @FATURAMENTOACUM