CREATE PROCEDURE CalculaIdade
AS
BEGIN
	UPDATE  [TABELA DE CLIENTES] SET IDADE = DATEDIFF(YEAR, [DATA DE NASCIMENTO], GETDATE())
END


INSERT INTO [dbo].[TABELA DE CLIENTES]
           ([CPF]
           ,[NOME]
           ,[ENDERECO 1]
           ,[BAIRRO]
           ,[CIDADE]
           ,[ESTADO]
           ,[CEP]
           ,[DATA DE NASCIMENTO]
           ,[SEXO]
           ,[LIMITE DE CREDITO]
           ,[VOLUME DE COMPRA]
           ,[PRIMEIRA COMPRA])
     VALUES
           ('12345678912',
           'JOÃO MACHADO',
           'RUA PROJETADA',
           'MADUREIRA',
		   'Rio de Janeiro',
		   'RJ',
		   '20001',
		   '20000306',
		   'M',
		   120000,
		   120000,
		   120000)

SELECT * FROM [TABELA DE CLIENTES] WHERE CPF = '12345678912'
EXEC CalculaIdade

/*EXERCICIO DE AULA*/

--CRIA O SELECT
SELECT * FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF ON NF.NUMERO = INF.NUMERO
INNER JOIN [TABELA DE PRODUTOS] TP ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
WHERE MONTH(NF.DATA) = 1 AND YEAR(NF.DATA) = 2017
AND TP.EMBALAGEM = 'Lata'


--CRIA O UPDATE
UPDATE NF SET NF.IMPOSTO = 0.18
FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF ON NF.NUMERO = INF.NUMERO
INNER JOIN [TABELA DE PRODUTOS] TP ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
WHERE MONTH(NF.DATA) = 1 AND YEAR(NF.DATA) = 2017
AND TP.EMBALAGEM = 'Lata'

--CRIA A PROCEDURE
CREATE PROCEDURE AtuakuzaImposto @MES_REFERENCIA AS INT, @ANO_REFERENCIA AS INT, @IMPOSTO AS FLOAT, @EMBALAGEM AS VARCHAR(10)
AS 
BEGIN
	UPDATE 
		NF SET NF.IMPOSTO = @IMPOSTO
	FROM [NOTAS FISCAIS] NF
		INNER JOIN [ITENS NOTAS FISCAIS] INF ON NF.NUMERO = INF.NUMERO
		INNER JOIN [TABELA DE PRODUTOS] TP ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
		WHERE MONTH(NF.DATA) = @MES_REFERENCIA AND YEAR(NF.DATA) = @ANO_REFERENCIA
	AND TP.EMBALAGEM = @EMBALAGEM
END

EXEC AtuakuzaImposto @MES_REFERENCIA = 2, @ANO_REFERENCIA = 2017, @IMPOSTO = 0.16, @EMBALAGEM = 'PET'

