/**
STORED PROCEDURE SEM MANIPULAÇÃO DE ERROS
**/

CREATE PROCEDURE InclusaoVendedor
	@MATRICULA AS VARCHAR(5),
	@NOME AS VARCHAR(100),
	@PERCENTUAL AS FLOAT,
	@DATAADMISSAO AS DATE,
	@FERIAS AS BIT,
	@BAIRRO AS VARCHAR(50)
AS
BEGIN
	INSERT INTO [TABELA DE VENDEDORES]
	(MATRICULA, NOME, [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
	VALUES(@MATRICULA, @NOME, @PERCENTUAL, @DATAADMISSAO, @FERIAS, @BAIRRO)
END

EXEC InclusaoVendedor 
	'00238', 
	'Pericles Alves',
	0.11,
	'20160821',
	0,
	'Santo Amaro'

/** STORED PROCEDURE COM TRATAMENTO DE ERRO **/
CREATE PROCEDURE InclusaoVendedor01
	@MATRICULA AS VARCHAR(5),
	@NOME AS VARCHAR(100),
	@PERCENTUAL AS FLOAT,
	@DATAADMISSAO AS DATE,
	@FERIAS AS BIT,
	@BAIRRO AS VARCHAR(50),
	@NUMERRO INT OUTPUT,
	@NUMLINHA INT OUTPUT
AS
BEGIN
	INSERT INTO [TABELA DE VENDEDORES]
	(MATRICULA, NOME, [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
	VALUES(@MATRICULA, @NOME, @PERCENTUAL, @DATAADMISSAO, @FERIAS, @BAIRRO)
	SELECT @NUMERRO=@@ERROR, @NUMLINHA=@@ROWCOUNT
END

--CHAMADA DE SP
DECLARE @NUMERRO INT
DECLARE @NUMLINHA INT
EXEC InclusaoVendedor01
	'00238', 
	'Pericles Alves',
	0.11,
	'20160821',
	0,
	'Santo Amaro',
	@NUMERRO = @NUMERRO OUTPUT,
	@NUMLINHA= @NUMLINHA OUTPUT
IF @NUMERRO <> 0
	PRINT 'hOUVE UM ERRO: '+ 
		CONVERT(VARCHAR(30), @NUMERRO) + ' - ' + CONVERT(VARCHAR(30), @NUMLINHA)