
CREATE PROCEDURE [dbo].[TrataErroZeroTry] 
	@CPF VARCHAR(12),
	@ANO INT,
	@DENOMINADOR INT,
	@MENSAGEM VARCHAR(50) OUTPUT
AS
BEGIN
	BEGIN TRY
		SELECT 
			SUM(A.QUANTIDADE * A.[PREÇO]) AS FATURAMENTO,
			SUM(A.QUANTIDADE * PREÇO)/@DENOMINADOR AS COMISSAO
		FROM [ITENS NOTAS FISCAIS] A INNER JOIN [NOTAS FISCAIS] B ON A.NUMERO=B.NUMERO 
		WHERE B.CPF=@CPF AND YEAR(B.DATA) = @ANO
	END TRY
	BEGIN CATCH
		SET @MENSAGEM = 'HOUVE UM ERRO: ' + CONVERT(VARCHAR(10),@@ERROR)
	END CATCH
END

DECLARE @DENOMINADOR INT
DECLARE @CPF VARCHAR(12)
DECLARE @ANO INT
DECLARE @MENSAGEM VARCHAR(30)

SET @CPF='1471156710'
SET @ANO=2016
SET @DENOMINADOR = 0
SET @MENSAGEM = ''
EXEC TrataErroZeroTry @CPF=@CPF, @ANO=@ANO, @DENOMINADOR=@DENOMINADOR, @MENSAGEM=@MENSAGEM OUTPUT
IF @MENSAGEM <> ''
	PRINT @MENSAGEM

/** EXERCICIO INLCUSAO DE VENDEDOR **/

CREATE PROCEDURE [dbo].[InclusaoVendedorTry]
	@MATRICULA AS VARCHAR(5),
	@NOME AS VARCHAR(100),
	@PERCENTUAL AS FLOAT,
	@DATAADMISSAO AS DATE,
	@FERIAS AS BIT,
	@BAIRRO AS VARCHAR(50),
	@MENSAGEM AS VARCHAR(50) OUTPUT
AS
BEGIN
	BEGIN TRY
		INSERT INTO [TABELA DE VENDEDORES](MATRICULA, NOME, [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
		VALUES(@MATRICULA, @NOME, @PERCENTUAL, @DATAADMISSAO, @FERIAS, @BAIRRO)
	END TRY
	BEGIN CATCH
		SET @MENSAGEM= 'HOUVE UM ERRO: '+ CONVERT(VARCHAR(50), @@ERROR)
	END CATCH
END