SELECT SUM(QUANTIDADE * [PREÇO]) FROM [ITENS NOTAS FISCAIS]
WHERE NUMERO =100


/* FUNÇÕES UDF - USER DEFINE FUNCTIION - CRIAÇÃO DE FUNÇÕES PERSONALIZADAS*/
CREATE FUNCTION FATURAMENTO_NOTA (@NUMERO AS INT) RETURNS FLOAT
AS
BEGIN
	DECLARE @FATURAMENTO FLOAT
	SELECT @FATURAMENTO = SUM(QUANTIDADE * [PREÇO]) FROM [ITENS NOTAS FISCAIS]
		WHERE NUMERO = @NUMERO
	RETURN @FATURAMENTO
END

SELECT NUMERO, [dbo].[FATURAMENTO_NOTA](NUMERO) AS FATURAMENTO FROM [NOTAS FISCAIS]

/* EXERCICIO AULA */

CREATE FUNCTION NUMERO_NOTAS (@DATA DATE) RETURNS INT
AS
BEGIN
	DECLARE @QUANTIDADE INT
	SELECT @QUANTIDADE = COUNT(*) FROM [NOTAS FISCAIS]
	 WHERE DATA = @DATA
	RETURN @QUANTIDADE
END

SELECT [dbo].[NUMERO_NOTAS] ('20170202')