SELECT * FROM [TABELA DE CLIENTES]

SELECT ESTADO, [LIMITE DE CREDITO] FROM [TABELA DE CLIENTES]

SELECT ESTADO, SUM([LIMITE DE CREDITO]) AS SOMA FROM [TABELA DE CLIENTES] 
GROUP BY ESTADO

SELECT ESTADO, AVG([LIMITE DE CREDITO]) AS MEDIA FROM [TABELA DE CLIENTES] 
GROUP BY ESTADO

SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) AS MAIOR_PREÇO FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM

SELECT EMBALAGEM, MIN([PREÇO DE LISTA]) AS MENOR_PREÇO FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM

SELECT EMBALAGEM, COUNT(*) AS MAIOR FROM [TABELA DE PRODUTOS] 
GROUP BY EMBALAGEM

SELECT BAIRRO, SUM([LIMITE DE CREDITO]) LIMITE FROM [TABELA DE CLIENTES]
WHERE ESTADO = 'SP' GROUP BY BAIRRO

/*
EXERCICIO
- QUANTOS ITENS DE VENDA EXISTEM COM A MAIOR QUANTIDADE DE VENDA PARA O PRODUTO '1101035'
*/

SELECT * FROM [ITENS NOTAS FISCAIS]

SELECT MAX([QUANTIDADE]) FROM [ITENS NOTAS FISCAIS]
WHERE [CODIGO DO PRODUTO] = '1101035'

SELECT COUNT([CODIGO DO PRODUTO]) QUANTIDADE FROM [ITENS NOTAS FISCAIS]
WHERE [CODIGO DO PRODUTO] = '1101035'
AND QUANTIDADE = 99