SELECT BAIRRO, ESTADO, SUM([LIMITE DE CREDITO]) AS SOMA_LIMITE FROM [TABELA DE CLIENTES]
WHERE ESTADO = 'SP' GROUP  BY BAIRRO, ESTADO
HAVING SUM([LIMITE DE CREDITO]) >= 140000


SELECT ESTADO, SUM([LIMITE DE CREDITO]) AS SOMA_LIMITE 
FROM [TABELA DE CLIENTES]
GROUP  BY BAIRRO, ESTADO

SELECT ESTADO, SUM([LIMITE DE CREDITO]) AS SOMA_LIMITE 
FROM [TABELA DE CLIENTES]
GROUP BY ESTADO
HAVING SUM([LIMITE DE CREDITO]) >= 850000

SELECT EMBALAGEM, SUM([PREÇO DE LISTA]) SOMA, MAX([PREÇO DE LISTA]) MAIOR, MIN([PREÇO DE LISTA])MENOR 
FROM [TABELA DE PRODUTOS]
GROUP BY EMBALAGEM

SELECT EMBALAGEM, SUM([PREÇO DE LISTA]) SOMA, MAX([PREÇO DE LISTA]) MAIOR, MIN([PREÇO DE LISTA])MENOR 
FROM [TABELA DE PRODUTOS]
GROUP BY EMBALAGEM
HAVING SUM([PREÇO DE LISTA]) <= 80

SELECT EMBALAGEM, SUM([PREÇO DE LISTA]) SOMA, MAX([PREÇO DE LISTA]) MAIOR, MIN([PREÇO DE LISTA])MENOR 
FROM [TABELA DE PRODUTOS]
GROUP BY EMBALAGEM
HAVING SUM([PREÇO DE LISTA]) <= 80 AND MAX([PREÇO DE LISTA]) >=6

SELECT  * FROM [NOTAS FISCAIS]

SELECT CPF, COUNT(*) QUANTIDADE FROM [NOTAS FISCAIS]
WHERE YEAR([DATA])=2016
GROUP BY CPF
HAVING COUNT(*)>2000