/****** Script do comando SelectTopNRows de SSMS  ******/
SELECT *  FROM [SUCOS_VENDAS].[dbo].[TABELA DE CLIENTES]

BEGIN TRANSACTION /*COMANDO QUE CRIA UM PONTO DE RESTAURAÇÃO*/

UPDATE [TABELA DE CLIENTES] SET [NOME] = 'TESTE'
WHERE CPF = '95939180787'

INSERT INTO [TABELA DE CLIENTES] (CPF, NOME, [ENDERECO 1], [ENDERECO 2], BAIRRO, CIDADE, ESTADO, CEP, [DATA DE NASCIMENTO], IDADE, SEXO, [LIMITE DE CREDITO], [VOLUME DE COMPRA],[PRIMEIRA COMPRA])
VALUES('12345678900', 'Nome Teste2','R Eduardo','END2','São', 'PAtro', 'MG', '3800000', '1990-04-18',32,'M',1000.00, 100, 0)

ROLLBACK /*RETORNA AO PONTO CRIADO PARA DESFAZER ALTERAÇÕES*/

COMMIT /* GRAVA ALTERAÇÕES REALIZADAS E APAGA PONTO BEGIN CRIADO */