
/*CRIAÇÃO DE TABELAS COM VALORES PADROES*/
CREATE TABLE TAB_PADRAO
(ID INT IDENTITY (1,1)NOT NULL,
DESCRITOR VARCHAR(20) NULL,
ENDERECO VARCHAR(200) NULL,
CIDADE VARCHAR(50) DEFAULT 'Cidade não definida',
DATA_CRIACAO DATE DEFAULT GETDATE())

SELECT * FROM TAB_PADRAO

/*INSERT COM CAMPOS PREENCHIDOS*/
INSERT INTO TAB_PADRAO (DESCRITOR, ENDERECO, CIDADE, DATA_CRIACAO) VALUES ('CLIENTE A', 'RUA DO A', 'SÃO PAULO', '2018-04-10')

/*INSERT QUE É COMPLEMENTADO COM OS VALORES PADORES*/
INSERT INTO TAB_PADRAO (DESCRITOR) VALUES ('CLIENTE B')