/*cria tabela com auto incremento iniciando em 1 e aumentando sempre + 1*/
CREATE TABLE TAB_IDENTITY
(ID INT IDENTITY(1,1) NOT NULL,
DESCRITOR VARCHAR(20) NULL)

/*inserindo registros*/
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE A')
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE B')
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE C')
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE D')
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ('CLIENTE E')

/*visualizar registrros criados*/
SELECT * FROM TAB_IDENTITY

/* apaga o primeiro registro e */
DELETE FROM TAB_IDENTITY WHERE ID = 1

/*apaga tabela*/
DROP TABLE TAB_IDENTITY

/*cria nova tabela em 100 e auto incrementa em 5 para cada insert*/
CREATE TABLE TAB_IDENTITY
(ID INT IDENTITY(100,5) NOT NULL,
DESCRITOR VARCHAR(20) NULL)
