SELECT CONVERT(VARCHAR, GETDATE(), 101) --MES /DIA / ANO

SELECT CONVERT(VARCHAR, GETDATE(), 113) -- DIA MES E ANO HH MM SS ML

SELECT CONVERT(VARCHAR, GETDATE(), 130) --DATA ARABE

SELECT CONVERT(decimal(10,5), 193.57) -- 5 CASAS DECIMAIS

SELECT * FROM [TABELA DE PRODUTOS]

/*ERRO POIS NAO HOUVE CONVERSAO DO  PREÇO DE LISTA (SMALLMONEY)*/
SELECT 'O preço do produto ' + [NOME DO PRODUTO] + ' é ' + [PREÇO DE LISTA] FROM [TABELA DE PRODUTOS]

/*QUERY CORRETA*/
SELECT 'O preço do produto ' + [NOME DO PRODUTO] + ' é ' + CONVERT(VARCHAR, [PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS]


/* EXERCICIO AULA -  LISTANDO EXPRESSÃO NATURAL */
SELECT * FROM [TABELA DE CLIENTES]

SELECT * FROM [ITENS NOTAS FISCAIS]

SELECT 
	CONCAT('O cliente: ' + TC.NOME + ' faturou ' + CONVERT(VARCHAR, CONVERT(DECIMAL(15,2), SUM(INF.QUANTIDADE * INF.[PREÇO]))), ' no ano ',
	CONVERT(VARCHAR, YEAR(NF.DATA))) AS SENTENCA
FROM 
	[NOTAS FISCAIS] NF
	INNER JOIN [ITENS NOTAS FISCAIS] INF ON (NF.NUMERO = INF.NUMERO)
	INNER JOIN [TABELA DE CLIENTES] TC ON (NF.CPF = TC.CPF)
WHERE 
	YEAR(DATA) = 2016
GROUP BY 
	TC.NOME, YEAR(DATA)



