/*TIPOS DE DELETES COM REGISTRO ESPECIFICO E POR GRUPO*/


SELECT * from [TABELA DE PRODUTOS] WHERE SUBSTRING([NOME DO PRODUTO],1,15) = 'Sabor dos Alpes'

DELETE FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1001000'

SELECT * FROM [TABELA DE PRODUTOS] WHERE TAMANHO ='1 litro' AND SUBSTRING([NOME DO PRODUTO],1,15) = 'Sabor dos Alpes'
DELETE FROM [TABELA DE PRODUTOS]  WHERE TAMANHO ='1 litro' AND SUBSTRING([NOME DO PRODUTO],1,15) = 'Sabor dos Alpes'

/*BAO PRATICA É FAZER UM SELECT ANTES DE EXECUTAR UM COMANDO DELETE*/
SELECT * FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] NOT IN (SELECT [CODIGO DO PRODUTO] FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS])
DELETE FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] NOT IN (SELECT [CODIGO DO PRODUTO] FROM [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS])

/*EXERCICIO*/
DELETE A FROM [NOTAS FISCAIS] A
INNER JOIN [TABELA DE CLIENTES] B ON A.CPF=B.CPF
WHERE B.IDADE < 18