SELECT CEILING (12.332323) --VALOR ABSOLUTO ARREDONDADO PARA CIMA

SELECT FLOOR(12.333223) -- VALOR ABSOLUTO ARREDONDADO PARA BAIXO

SELECT RAND() -- NUMERO ALEATORIO

SELECT ROUND(12.33323323,2) --ARREDONDA PARA APENAS DUAS CASAS DECIMAIS


SELECT [QUANTIDADE], [PREÇO], ROUND(([QUANTIDADE] * PREÇO), 2) 'TOTAL EM PRODUTOS' 
FROM [ITENS NOTAS FISCAIS]

SELECT YEAR(DATA) ANO, FLOOR(SUM(IMPOSTO * ([QUANTIDADE] * [PREÇO]))) FATURAMENTO
FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA) = 2016
GROUP BY YEAR(DATA)


