/*
	ESTUDOS DE FUNCÇÕES SQL SERVER
	FUNÇÕES ESCALARES OU FUNÇÕES SUBSTRING

*/

--RETIRA ESPAÇOS ANTES DA STRING
SELECT LTRIM ('    OLA')
 
-- RETIRA ESPAÇÕES A DIREITA DA STRING
SELECT RTRIM ('OLA    ')

-- CONCATENA DUAS VARCHAR
SELECT CONCAT('OLA ', 'TUDO BEM')

--CONCATENA USANDO OPERADOR +
SELECT 'OLA ' + 'TUDO BEM'

-- SELECIONA CARACTERES A ESQUERDA
SELECT LEFT ('RUA AUGUSTA', 3)

--SELECIONA CARACTERES A DIREITA
SELECT RIGHT ('RUA AUGUSTA',7)

--CONVERTE TODO VARCHAR PARA UPPERCASE
SELECT UPPER('rua agusuta')

--CONVERTE O VARCHAR EM LOWWERCASE
SELECT LOWER ('RUA AUGUSTA')

-- UTILIZA PARA SUBISTITUIR, O CAMPO A TRABALHAR, O TRECHO QUE BUSCA E QUEM O SUBSTITUIRÁ
SELECT REPLACE('R. AUGUSTA', 'R.', 'RUA')

-- POSSILITA BUSCAR POR NUMERO DE CARATERES, POR POSICOES DOS CARACTERES
SELECT SUBSTRING('RUA AUGUSTA',1,3)
SELECT SUBSTRING('RUA AUGUSTA',2,4)


-- RETORNA O TAMANHO DO CAMPO
SELECT LEN('RUA AUGUSTA')

SELECT * FROM [TABELA DE CLIENTES]
SELECT CONCAT(NOME, ' (', CPF, ') ') AS NOME_CPF FROM [TABELA DE CLIENTES]

SELECT CONCAT(NOME, ' - ', [ENDERECO 1], ' - ', BAIRRO, ' - ', CIDADE, ' - ', ESTADO) AS DADOS_COMPLETOS FROM [TABELA DE CLIENTES]

