SELECT CEILING (12.332323) --VALOR ABSOLUTO ARREDONDADO PARA CIMA

SELECT FLOOR(12.333223) -- VALOR ABSOLUTO ARREDONDADO PARA BAIXO

SELECT RAND() -- NUMERO ALEATORIO

SELECT ROUND(12.33323323,2) --ARREDONDA PARA APENAS DUAS CASAS DECIMAIS


SELECT [QUANTIDADE], [PREÇO], ROUND(([QUANTIDADE] * PREÇO), 2) 'TOTAL EM PRODUTOS' 
FROM [ITENS NOTAS FISCAIS]
