SELECT * FROM [TABELA DE CLIENTES]
INNER JOIN  [NOTAS FISCAIS] ON [TABELA DE CLIENTES].CPF= [NOTAS FISCAIS].CPF

SELECT * FROM [TABELA DE CLIENTES]

SELECT [TABELA DE CLIENTES].NOME, COUNT (*) FROM [TABELA DE CLIENTES]
INNER JOIN [NOTAS FISCAIS] ON [TABELA DE CLIENTES].CPF= [NOTAS FISCAIS].CPF
GROUP BY [TABELA DE CLIENTES].NOME

SELECT [TABELA DE CLIENTES].NOME, COUNT (*) FROM [TABELA DE CLIENTES]
LEFT JOIN [NOTAS FISCAIS] ON [TABELA DE CLIENTES].CPF= [NOTAS FISCAIS].CPF
GROUP BY [TABELA DE CLIENTES].NOME

SELECT [TABELA DE CLIENTES].CPF, [TABELA DE CLIENTES].NOME, COUNT (*) FROM [TABELA DE CLIENTES]
LEFT JOIN [NOTAS FISCAIS] ON [TABELA DE CLIENTES].CPF= [NOTAS FISCAIS].CPF
GROUP BY [TABELA DE CLIENTES].CPF, [TABELA DE CLIENTES].NOME