SELECT TP.SABOR FROM [TABELA DE PRODUTOS] TP

SELECT NF.DATA FROM [NOTAS FISCAIS] NF

SELECT (INF.QUANTIDADE * INF.PREÇO) FROM [ITENS NOTAS FISCAIS] INF


/* 1 - CONSULTA CON JOINS SIMPLES*/
SELECT 
	TP.SABOR,
	NF.DATA,
	(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM
	[ITENS NOTAS FISCAIS] INF 
	INNER JOIN [TABELA DE PRODUTOS] TP ON (TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO])
	INNER JOIN [NOTAS FISCAIS] NF ON (NF.NUMERO = INF.NUMERO)


/*2 - CONSULTA COM AGRUPAMENTO*/
SELECT 
	TP.SABOR,
	YEAR(NF.DATA) ANO,
	SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM
	[ITENS NOTAS FISCAIS] INF 
	INNER JOIN [TABELA DE PRODUTOS] TP ON (TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO])
	INNER JOIN [NOTAS FISCAIS] NF ON (NF.NUMERO = INF.NUMERO)
GROUP BY
	TP.SABOR,
	YEAR(NF.DATA)

/*3 - CONSULTA COM FILTRO*/
SELECT 
	TP.SABOR,
	YEAR(NF.DATA) ANO,
	SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM
	[ITENS NOTAS FISCAIS] INF 
	INNER JOIN [TABELA DE PRODUTOS] TP ON (TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO])
	INNER JOIN [NOTAS FISCAIS] NF ON (NF.NUMERO = INF.NUMERO)
WHERE
	YEAR(NF.DATA) = 2016
GROUP BY
	TP.SABOR,
	YEAR(NF.DATA)


/*3 - CONSULTA COM PERCENTUAL*/
SELECT 
	TP.SABOR,
	YEAR(NF.DATA) ANO,
	SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM
	[ITENS NOTAS FISCAIS] INF 
	INNER JOIN [TABELA DE PRODUTOS] TP ON (TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO])
	INNER JOIN [NOTAS FISCAIS] NF ON (NF.NUMERO = INF.NUMERO)
WHERE
	YEAR(NF.DATA) = 2016
GROUP BY
	TP.SABOR,
	YEAR(NF.DATA)


	/*SELECT TOTAL DO ANO*/
SELECT 
	YEAR(NF.DATA) ANO,
	SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM
	[ITENS NOTAS FISCAIS] INF 
	INNER JOIN [TABELA DE PRODUTOS] TP ON (TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO])
	INNER JOIN [NOTAS FISCAIS] NF ON (NF.NUMERO = INF.NUMERO)
WHERE
	YEAR(NF.DATA) = 2016
GROUP BY
	YEAR(NF.DATA)

/*SELECT FINAL */
SELECT 
	TB1.SABOR, 
	TB1.ANO,
	CONVERT(DECIMAL(15,2), TB1.FATURAMENTO) AS FATURAMENTO,
	CONVERT (VARCHAR, CONVERT(DECIMAL (15,2),(TB1.FATURAMENTO/TB2.TOTAL)*100)) +'%' AS PERCENTUAL
FROM
	(SELECT 
		TP.SABOR,
		YEAR(NF.DATA) ANO,
		SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
	FROM
		[ITENS NOTAS FISCAIS] INF 
		INNER JOIN [TABELA DE PRODUTOS] TP ON (TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO])
		INNER JOIN [NOTAS FISCAIS] NF ON (NF.NUMERO = INF.NUMERO)
	WHERE
		YEAR(NF.DATA) = 2016
	GROUP BY
		TP.SABOR,
		YEAR(NF.DATA)) TB1
		
		INNER JOIN (
		SELECT 
			YEAR(NF.DATA) ANO,
			SUM(INF.QUANTIDADE * INF.PREÇO) AS TOTAL
		FROM
			[ITENS NOTAS FISCAIS] INF 
			INNER JOIN [TABELA DE PRODUTOS] TP ON (TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO])
			INNER JOIN [NOTAS FISCAIS] NF ON (NF.NUMERO = INF.NUMERO)
		WHERE
			YEAR(NF.DATA) = 2016
		GROUP BY
			YEAR(NF.DATA)) TB2 ON (TB1.ANO = TB2.ANO)
ORDER BY 
	TB1.FATURAMENTO DESC
