SELECT * FROM  [TABELA DE PRODUTOS]

SELECT * FROM  [TABELA DE PRODUTOS]
WHERE [NOME DO PRODUTO] LIKE '%LITROS%'

SELECT * FROM  [TABELA DE PRODUTOS]
WHERE [NOME DO PRODUTO] LIKE 'LITROS%'

SELECT * FROM  [TABELA DE PRODUTOS]
WHERE [NOME DO PRODUTO] LIKE 'LINHA%'

SELECT * FROM  [TABELA DE PRODUTOS]
WHERE [NOME DO PRODUTO] LIKE '%LITROS%' AND [SABOR] = 'LARANJA'