SELECT NOME, BAIRRO FROM [TABELA DE VENDEDORES]

SELECT NOME, BAIRRO FROM [TABELA DE CLIENTES]
WHERE BAIRRO IN (SELECT  BAIRRO FROM [TABELA DE VENDEDORES])

SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

SELECT NOVA_CONSULTA.EMBALAGEM, NOVA_CONSULTA.MAX_PRECO
FROM (SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) AS MAX_PRECO FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM) NOVA_CONSULTA
WHERE NOVA_CONSULTA.MAX_PRECO <=5

SELECT CPF, COUNT(*) AS QUANTIDADE FROM [NOTAS FISCAIS] AS NF 
WHERE YEAR(DATA) = 2016
GROUP BY CPF

SELECT  NOVA.CPF, NOVA.QUANTIDADE, NOVA.ANO
FROM (SELECT CPF, COUNT(*) AS QUANTIDADE, YEAR(DATA) ANO FROM [NOTAS FISCAIS] AS NF GROUP BY CPF, YEAR(DATA)) NOVA
WHERE NOVA.QUANTIDADE > 2000 AND NOVA.ANO>2016 
/*SOLUÇÃO COM ERRO*/

SELECT NOVA.CPF, NOVA.CONTADOR 
FROM (SELECT CPF, COUNT(*) AS CONTADOR FROM [NOTAS FISCAIS] WHERE YEAR(DATA) = 2016 GROUP BY CPF)NOVA 
WHERE NOVA.CONTADOR>2000