
CREATE TABLE TAB_FATURAMENTO
(DATA_VENDA DATE NULL,
TOTAL_VENDA FLOAT)

CREATE TRIGGER TG_ITENS_VENDIDOS
ON [ITENS NOTAS FISCAIS]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN

DELETE FROM TAB_FATURAMENTO;

INSERT INTO TAB_FATURAMENTO (DATA_VENDA, TOTAL_VENDA)
SELECT A.DATA AS DATA_VENDA, SUM(B.QUANTIDADE * B.[PREÇO]) AS TOTAL_VENDA
FROM [NOTAS FISCAIS] A INNER JOIN [ITENS NOTAS FISCAIS] B
ON A.NUMERO = B.NUMERO
GROUP BY A.DATA;

END;

INSERT INTO [NOTAS FISCAIS] (NUMERO, DATA, CPF, MATRICULA, IMPOSTO)
VALUES ('0100', '2018-05-15', '1471156710', '235', 0.18)

INSERT INTO [ITENS NOTAS FISCAIS] ([NUMERO],[CODIGO DO PRODUTO],[QUANTIDADE],[PREÇO])
VALUES ('0100', '1000889', 100, 1)
INSERT INTO [ITENS NOTAS FISCAIS] ([NUMERO],[CODIGO DO PRODUTO],[QUANTIDADE],[PREÇO])
VALUES ('0100', '1002334', 100, 1)


SELECT * FROM TAB_FATURAMENTO

INSERT INTO [NOTAS FISCAIS] (NUMERO, DATA, CPF, MATRICULA, IMPOSTO)
VALUES ('0101', '2018-05-15', '1471156710', '235', 0.18)

INSERT INTO [ITENS NOTAS FISCAIS] ([NUMERO],[CODIGO DO PRODUTO],[QUANTIDADE],[PREÇO])
VALUES ('0101', '1000889', 100, 1)
INSERT INTO [ITENS NOTAS FISCAIS] ([NUMERO],[CODIGO DO PRODUTO],[QUANTIDADE],[PREÇO])
VALUES ('0101', '1002334', 100, 1)

INSERT INTO [NOTAS FISCAIS] (NUMERO, DATA, CPF, MATRICULA, IMPOSTO)
VALUES ('0102', '2018-05-16', '1471156710', '235', 0.18)

INSERT INTO [ITENS NOTAS FISCAIS] ([NUMERO],[CODIGO DO PRODUTO],[QUANTIDADE],[PREÇO])
VALUES ('0102', '1000889', 100, 1.5)
INSERT INTO [ITENS NOTAS FISCAIS] ([NUMERO],[CODIGO DO PRODUTO],[QUANTIDADE],[PREÇO])
VALUES ('0102', '1002334', 200, 1)

DELETE FROM [ITENS NOTAS FISCAIS] WHERE [NUMERO] = '0102' AND [CODIGO DO PRODUTO] = '1002334'

UPDATE [ITENS NOTAS FISCAIS] SET [QUANTIDADE] = 300 WHERE [NUMERO] = '0102' AND [CODIGO DO PRODUTO] = '1000889'


-- EXERCICIIO --
CREATE TRIGGER TG_CLIENTES_IDADE
ON [TABELA DE CLIENTES]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
UPDATE [TABELA DE CLIENTES] SET [IDADE] = DATEDIFF(YEAR, [DATA DE NASCIMENTO], GETDATE());
END;









