SELECT * FROM [TABELA DE PRODUTOS]

/*UPDATE SIMPLES*/
UPDATE [TABELA DE PRODUTOS] SET [PREÇO DE LISTA] = 6
WHERE [CODIGO DO PRODUTO] = '1000889'

/*UPDATE GRUPO*/
UPDATE [TABELA DE PRODUTOS] SET SABOR = 'Laranja', [EMBALAGEM] = 'pet'
WHERE [CODIGO DO PRODUTO] = '1000889'

/*UPDATE EM LOTE OOU CONJUNTO*/
SELECT * FROM [TABELA DE PRODUTOS]
WHERE [SABOR] = 'Maracujá'

UPDATE [TABELA DE PRODUTOS] SET [PREÇO DE LISTA] = [PREÇO DE LISTA] * 1.10
WHERE [SABOR] = 'Maracujá'

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [SABOR] = 'Maracujá'

/*ECERCICIO 1 */
SELECT * FROM [TABELA DE CLIENTES]
WHERE CPF = '19290992743'

UPDATE [TABELA DE CLIENTES] 
SET [ENDERECO 1] = 'R. Jorge Emilio 23', [BAIRRO] = 'Santo Amaro', [CIDADE] = 'São Paulo', ESTADO = 'SP', CEP = 8833223
WHERE CPF = '19290992743'

SELECT * FROM [TABELA DE CLIENTES]
WHERE CPF = '19290992743'

/*exercicio 2*/
UPDATE [TABELA DE CLIENTES]
SET [VOLUME DE COMPRA] = [VOLUME DE COMPRA] * 1.2
WHERE [ESTADO] = 'RJ'