SELECT * FROM [SUCOS_VENDAS].[dbo].[TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO]= '1000889'

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO]= '1000889'

UPDATE [SUCOS_VENDAS].[dbo].[TABELA DE PRODUTOS] SET [PREÇO DE LISTA] = 7
WHERE [CODIGO DO PRODUTO]= '1000889'

/*SELECT PARA MOSTRAR RESULTADOS JUNTOS ANTES DO UPDATE*/
SELECT B.[CODIGO DO PRODUTO], B.[PREÇO DE LISTA], A.[CODIGO DO PRODUTO], A.[PREÇO DE LISTA]
FROM [TABELA DE PRODUTOS] A 
INNER JOIN [SUCOS_VENDAS].[dbo].[TABELA DE PRODUTOS]B
ON (A.[CODIGO DO PRODUTO] = B.[CODIGO DO PRODUTO])
WHERE A.[CODIGO DO PRODUTO]='1000889'


/*UPDATE COM FROM, VINCULANDO TABELA RAIZ COM TABELA IMPORTADA*/
UPDATE A SET A.[PREÇO DE LISTA] = B.[PREÇO DE LISTA]
FROM [TABELA DE PRODUTOS] A 
INNER JOIN [SUCOS_VENDAS].[dbo].[TABELA DE PRODUTOS]B
ON (A.[CODIGO DO PRODUTO] = B.[CODIGO DO PRODUTO])
WHERE A.[CODIGO DO PRODUTO]='1000889'


